# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: build-and-test-Post

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      working-directory: ./Reclone-Post-Services
      run: dotnet restore

    - name: Build
      working-directory: ./Reclone-Post-Services
      run: dotnet build --configuration Release

    - name: Test
      working-directory: ./Reclone-Post-Services
      run: dotnet test --no-restore --verbosity normal
