name: Build and deploy ASP.Net Core app to Azure Web App - ReclonePostService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        working-directory: ./Reclone-Post-Services
        run: dotnet restore

      - name: Build
        working-directory: ./Reclone-Post-Services
        run: dotnet build --configuration Release

  jobs: 
    sonarQube Build and analyze:
        runs-on: windows-latest
        steps:
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: 11
              distribution: 'zulu' # Alternative distribution options are available.
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0  # Shallow clones should be disabled for better analysis relevance
          - name: Cache SonarCloud packages
            uses: actions/cache@v2
            with:
              path: ~/sonar/cache
              key: ${{ runner.os }}-sonar
              restore-keys: ${{ runner.os }}-sonar
          - name: Cache SonarCloud scanner
            id: cache-sonar-scanner
            uses: actions/cache@v2
            with:
              path: ./.sonar/scanner
              key: ${{ runner.os }}-sonar-scanner
              restore-keys: ${{ runner.os }}-sonar-scanner
          - name: Install SonarCloud scanner
            if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
            shell: powershell
            run: |
              New-Item -Path ./.sonar/scanner -ItemType Directory
              dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
          - name: Build and analyze
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            shell: powershell
            run: |
              ./.sonar/scanner/dotnet-sonarscanner begin /k:"Blodowica_Reclone-Post-Services" /o:"blodowica" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
              <insert_your_clean_build_command>
              ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

          - name: Test
            working-directory: ./Reclone-Post-Services
            run: dotnet test --no-restore --verbosity normal

          - name: dotnet publish
            working-directory: ./Reclone-Post-Services/Reclone-BackEnd
            run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp --self-contained --runtime linux-x64
          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v2
            with:
              name: .net-app
              path: ${{env.DOTNET_ROOT}}/myapp

        deploy:
          runs-on: windows-latest
          needs: build-and-test
          environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

          steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                name: .net-app

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'ReclonePostService'
                slot-name: 'Production'
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_444E926CB26548D694167112D07A9EEC }}
                package: .
