name: Build and deploy ASP.Net Core app to Azure Web App - ReclonePostService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        working-directory: ./Reclone-Post-Services
        run: dotnet restore

      - name: Build
        working-directory: ./Reclone-Post-Services
        run: dotnet build --configuration Release

      - name: Test
        working-directory: ./Reclone-Post-Services
        run: dotnet test --no-restore --verbosity normal

      - name: dotnet publish
        working-directory: ./Reclone-Post-Services/Reclone-BackEnd
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp --self-contained --runtime linux-x64

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ReclonePostService'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_444E926CB26548D694167112D07A9EEC }}
          package: .
